import { Router, type IRouter } from "express";
import classAccessRouter from "../modules/class-access/routes";
import classDayRouter from "../modules/class-day/routes";
import classTopicRouter from "../modules/class-topic/routes";
import contentRouter from "../modules/content/routes";
import identityRouter from "../modules/identity/routes";
import schoolContextRouter from "../modules/school-context/routes";
import studentAssignmentRouter from "../modules/student-assignment/routes";
import studentPlanRouter from "../modules/student-plan/routes";
import studentProgressRouter from "../modules/student-progress/routes";
import assessmentRouter from "../modules/assessment/routes";
import scheduleRouter from "../modules/schedule/routes";
import productiveAssessmentRouter from "../modules/productive-assessment/routes";
import quizRouter from "../modules/quiz/routes";
import studentContentRouter from "../modules/student-content/routes";
import studentLearningRouter from "../modules/student-learning/routes";
import teacherDashboardRouter from "../modules/teacher-dashboard/routes";
import healthRouter from "./health";

const router: IRouter = Router();

router.use(healthRouter);
router.use(identityRouter);
router.use(contentRouter);
router.use(classAccessRouter);
router.use(classDayRouter);
router.use(classTopicRouter);
router.use(schoolContextRouter);
router.use(studentAssignmentRouter);
router.use(studentPlanRouter);
router.use(studentProgressRouter);
router.use(assessmentRouter);
router.use(scheduleRouter);
router.use(productiveAssessmentRouter);
router.use(quizRouter);
router.use(studentContentRouter);
router.use(studentLearningRouter);
router.use(teacherDashboardRouter);

export default router;
