// Schema exports — the live ej_learning_dev database only.
//
// `database.ts` and `relations.ts` are generated by
// `pnpm --filter @workspace/db run introspect`. They are the single source of
// truth for the 26 tables, 8 enums and 5 views the product uses across the
// core/content/learning/assessment/staging/audit schemas. Regenerate them
// rather than hand-editing.
//
// drizzle-kit reads this file to plan migrations. Anything exported here that
// is absent from the database becomes a CREATE TABLE in the next migration, so
// definitions for tables that do not exist belong in ./legacy.ts instead.
export * from "./database";
export * from "./relations";
