// Schema exports - the live ej_learning_dev database only.
//
// `database.ts` and `relations.ts` were generated by `drizzle-kit introspect`
// as the baseline for the 26 tables, 8 enums and 5 views that already existed
// across the core/content/learning/assessment/staging/audit schemas. From that
// baseline on, this directory is hand-maintained: change a table here, then
// `generate` and `migrate`. Re-introspect only to pick up a change made to the
// database outside a migration.
//
// drizzle-kit reads this file to plan migrations. Anything exported here that
// is absent from the database becomes a CREATE TABLE in the next migration, so
// definitions for tables that do not exist belong in ./legacy.ts instead.
export * from "./proficiency";
export * from "./database";
export * from "./relations";
export * from "./identity";
export * from "./scheduling";
export * from "./quiz";
